//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkWithCustomer.Models
{
    public class Cusf
    {
        public string CNAME { get; set; }
        public string DSDCDE { get; set; }
        public string STATUS { get; set; }
        public string TELNO { get; set; }
        public string EXTN { get; set; }
        public decimal LCTDAT { get; set; }
        public decimal APDATE { get; set; }
        public string USERNM { get; set; }
        public string SALUT { get; set; }
        public string JTITLE { get; set; }
        public string FAXNO { get; set; }
        public string EMAIL { get; set; }
        public string WEBSIT { get; set; }
        public string ADD1 { get; set; }
        public string ADD2 { get; set; }
        public string ADD3 { get; set; }
        public string ADD4 { get; set; }
        public string CNTRY { get; set; }
        public string PSCD { get; set; }
        public decimal CUSNO { get; set; }
        public string CMMNT1 { get; set; }
        public string CMMNT2 { get; set; }
        public string CMMNT3 { get; set; }
        public string DOCRCD { get; set; }
        public string DOC2 { get; set; }
        public string DOC3 { get; set; }
        public string DOC4 { get; set; }
        public string DOC5 { get; set; }
        public string DOC6 { get; set; }
        public string OLDMCH { get; set; }
        public string PRPCDE { get; set; }
        public string LSLCDE { get; set; }
        public string PREFIX { get; set; }
        public decimal LLETSQ { get; set; }
        public string SPREQ { get; set; }
        public string RISC { get; set; }
        public string ALTTEL { get; set; }
        public string ALTTL2 { get; set; }
        public string SINIT { get; set; }
        public string VERYFD { get; set; }
        public string VINIT { get; set; }
        public decimal VFDATE { get; set; }
        public string CRTNAM { get; set; }
        public decimal CRTDAT { get; set; }
        public string UPDNAM { get; set; }
        public decimal UPDDAT { get; set; }
        public decimal ORG { get; set; }
    }
}