//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;

namespace WorkWithCustomer.Models
{
    public class Purchases
    {
        private decimal _amt_last_sale;
        private string _b_o = "";
        private decimal _balance;
        private decimal _bank;
        private decimal _bank_a_c;
        private DateTime _chg_date = DateTime.Today;
        private string _cr_guarantee = "";
        private decimal _credit_limit;
        private decimal _curr_claim;
        private decimal _curr_cost;
        private decimal _curr_pay;
        private decimal _curr_sls;
        private decimal _current_amt;
        private string _cusgrp = "";
        private string _customer = "";
        private DateTime _date_last_pay = DateTime.Today;
        private DateTime _date_last_stmt = DateTime.Today;
        private DateTime _date_loaded = DateTime.Today;
        private string _distributor = "";
        private string _forex = "";
        private string _int_x = "";
        private string _lang = "";
        private decimal _last_pay;
        private DateTime _last_sale = DateTime.Today;
        private decimal _last_year_sls;
        private string _name = "";
        private string _related_account = "";
        private string _rep = "";
        private string _statement_account = "";
        private string _stl_dsc = "";
        private string _tax_reg = "";
        private string _terms = "";
        private decimal _x030_days;
        private decimal _x060_days;
        private decimal _x090_days;
        private decimal _x120_days;
        private decimal _x150_days;
        private decimal _x180_days;
        private decimal _ytd_sales;

        [Display(Name = "Customer No.")]
        public string customer
        {
            get { return _customer; }
            set { if (value != null) _customer = value; }
        }

        [Display(Name = "Customer Name")]
        public string name
        {
            get { return _name; }
            set { if (value != null) _name = value; }
        }

        [Display(Name = "Statement Account")]
        public string statement_account
        {
            get { return _statement_account; }
            set { if (value != null) _statement_account = value; }
        }

        [Display(Name = "Related Account")]
        public string related_account
        {
            get { return _related_account; }
            set { if (value != null) _related_account = value; }
        }

        [Display(Name = "Tax Reg")]
        public string tax_reg
        {
            get { return _tax_reg; }
            set { if (value != null) _tax_reg = value; }
        }

        [Display(Name = "Bank")]
        public decimal? bank
        {
            get { return _bank; }
            set { if (value != null) _bank = (decimal) value; }
        }

        [Display(Name = "Bank A/c")]
        public decimal? bank_a_c
        {
            get { return _bank_a_c; }
            set { if (value != null) _bank_a_c = (decimal) value; }
        }

        [Display(Name = "Forex")]
        public string forex
        {
            get { return _forex; }
            set { if (value != null) _forex = value; }
        }

        [Display(Name = "CusGrp")]
        public string cusgrp
        {
            get { return _cusgrp; }
            set { if (value != null) _cusgrp = value; }
        }

        [Display(Name = "Rep")]
        public string rep
        {
            get { return _rep; }
            set { if (value != null) _rep = value; }
        }

        [Display(Name = "Distributor")]
        public string distributor
        {
            get { return _distributor; }
            set { if (value != null) _distributor = value; }
        }

        [Display(Name = "Terms")]
        public string terms
        {
            get { return _terms; }
            set { if (value != null) _terms = value; }
        }

        [Display(Name = "Credit Limit")]
        public decimal? credit_limit
        {
            get { return _credit_limit; }
            set { if (value != null) _credit_limit = (decimal) value; }
        }

        [Display(Name = "Stl Dsc")]
        public string stl_dsc
        {
            get { return _stl_dsc; }
            set { if (value != null) _stl_dsc = value; }
        }

        [Display(Name = "Int")]
        public string int_x
        {
            get { return _int_x; }
            set { if (value != null) _int_x = value; }
        }

        [Display(Name = "Cr Guarantee")]
        public string cr_guarantee
        {
            get { return _cr_guarantee; }
            set { if (value != null) _cr_guarantee = value; }
        }

        [Display(Name = "B/O")]
        public string b_o
        {
            get { return _b_o; }
            set { if (value != null) _b_o = value; }
        }

        [Display(Name = "Lang")]
        public string lang
        {
            get { return _lang; }
            set { if (value != null) _lang = value; }
        }

        [DataType(DataType.Date)]
        [Display(Name = "Date Loaded")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime? date_loaded
        {
            get { return _date_loaded; }
            set { if (value != null) _date_loaded = (DateTime) value; }
        }

        [DataType(DataType.Date)]
        [Display(Name = "Chg-Date")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime? chg_date
        {
            get { return _chg_date; }
            set { if (value != null) _chg_date = (DateTime) value; }
        }

        [DataType(DataType.Date)]
        [Display(Name = "Last Sale")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime? last_sale
        {
            get { return _last_sale; }
            set { if (value != null) _last_sale = (DateTime) value; }
        }

        [Display(Name = "Amount Last Sale")]
        public decimal? amt_last_sale
        {
            get { return _amt_last_sale; }
            set { if (value != null) _amt_last_sale = (decimal) value; }
        }

        [DataType(DataType.Date)]
        [Display(Name = "Date Last Pay")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime? date_last_pay
        {
            get { return _date_last_pay; }
            set { if (value != null) _date_last_pay = (DateTime) value; }
        }

        [Display(Name = "Last Pay")]
        public decimal? last_pay
        {
            get { return _last_pay; }
            set { if (value != null) _last_pay = (decimal) value; }
        }

        [DataType(DataType.Date)]
        [Display(Name = "Date Last Statement")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime? date_last_stmt
        {
            get { return _date_last_stmt; }
            set { if (value != null) _date_last_stmt = (DateTime) value; }
        }

        [Display(Name = "Current Pay")]
        public decimal? curr_pay
        {
            get { return _curr_pay; }
            set { if (value != null) _curr_pay = (decimal) value; }
        }

        [Display(Name = "Current Claim")]
        public decimal? curr_claim
        {
            get { return _curr_claim; }
            set { if (value != null) _curr_claim = (decimal) value; }
        }

        [Display(Name = "Current Sales")]
        public decimal? curr_sls
        {
            get { return _curr_sls; }
            set { if (value != null) _curr_sls = (decimal) value; }
        }

        [Display(Name = "Current Cost")]
        public decimal? curr_cost
        {
            get { return _curr_cost; }
            set { if (value != null) _curr_cost = (decimal) value; }
        }

        [Display(Name = "Ytd Sales")]
        public decimal? ytd_sales
        {
            get { return _ytd_sales; }
            set { if (value != null) _ytd_sales = (decimal) value; }
        }

        [Display(Name = "Last Year Sales")]
        public decimal? last_year_sls
        {
            get { return _last_year_sls; }
            set { if (value != null) _last_year_sls = (decimal) value; }
        }

        [Display(Name = "Balance")]
        public decimal? balance
        {
            get { return _balance; }
            set { if (value != null) _balance = (decimal) value; }
        }

        [Display(Name = "Current Amount")]
        public decimal? current_amt
        {
            get { return _current_amt; }
            set { if (value != null) _current_amt = (decimal) value; }
        }

        [Display(Name = "X30_days")]
        public decimal? x030_days
        {
            get { return _x030_days; }
            set { if (value != null) _x030_days = (decimal) value; }
        }

        [Display(Name = "X60_days")]
        public decimal? x060_days
        {
            get { return _x060_days; }
            set { if (value != null) _x060_days = (decimal) value; }
        }

        [Display(Name = "X90_days")]
        public decimal? x090_days
        {
            get { return _x090_days; }
            set { if (value != null) _x090_days = (decimal) value; }
        }

        [Display(Name = "X20_days")]
        public decimal? x120_days
        {
            get { return _x120_days; }
            set { if (value != null) _x120_days = (decimal) value; }
        }

        [Display(Name = "X50_days")]
        public decimal? x150_days
        {
            get { return _x150_days; }
            set { if (value != null) _x150_days = (decimal) value; }
        }

        [Display(Name = "X80_days")]
        public decimal? x180_days
        {
            get { return _x180_days; }
            set { if (value != null) _x180_days = (decimal) value; }
        }

        [Display(Name = "Prospect No.")]
        public decimal? prospect_no { get; set; }
    }
}